version=1.0.0
group=net.ninjadev
java_version=25

# Minecraft/Common
minecraft_version=26.1.2
mod_name=NinjaMulti
mod_author=NinjaDev
mod_id=ninjamulti
license=MIT
credits=
description=Multi-loader API for Minecraft modding
minecraft_version_range=[26.1.2]
neo_form_version=26.1-1

# Fabric
fabric_version=0.147.0+26.1.2
fabric_loader_version=0.19.2

# Forge
forge_version=64.0.6
forge_loader_version_range=[64,)

# NeoForge
neoforge_version=26.1.2.22-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
